### ISSUE TITLE
Don't suggest if weight >10 000

### ISSUE THREAD

**Issue by snomos** [divvun/divvunspell#10]
Everything with such high weights are intentionally so, and should not be suggested. Implementing that limit will remove a lot of noise from the speller.

In the long run the weight limit for no-sugg should be configurable via the zhfst file, but for now it is ok to just hard-code it.

**Comment by bbqsrc** [comment]
This is already supported and the library defaults to <10000. Do you want the command line tool to default to that as well?

**Comment by snomos** [comment]
Yes, at best with an option to override. More precisely, the command line tool (or the library) used for the accuracy testing must mirror the behavior of the actual spellers - otherwise the testing is only halfway useful.

**Comment by bbqsrc** [comment]
Added with default max weight of 10000. Can use `-w 0` on command line to remove weight caps.
