### ISSUE TITLE
Provide alphabet to tokeniser

### ISSUE THREAD

**Issue by bbqsrc** [divvun/divvunspell#11]
Some languages are going to consider dashes etc as characters of their alphabet, so we should override Unicode's categories for this case by providing the alphabet from a transducer as the primary source of truth of what belongs in a "word".

**Comment by snomos** [comment]
Try this to repeat:

```
echo 'nah-namisk' | divvunspell -sS -z /Library/Services/crk.bundle/Contents/Resources/crk-Latn-x-macron.zhfst 
```

Install the `zhfst` file using the Divvun installer.
