### ISSUE TITLE
Missing README and usage

### ISSUE THREAD

**Issue by eddieantonio** [divvun/divvunspell#2]
Hello! I was wondering if there could be a simple getting started guide in the README that would explain how to embed this in mobile applications. Currently, there is no README or LICENSE.

**EDIT**: To clarify, I'm try to see if this implementation is viable to embed within a predictive text engine for mobile platforms. However, I need a license to determine if I can use it at all. As well, most open source libraries I would need the bare minimum of documentation (entry points, example on how to link with my application). Adding both a simple README and LICENSE will go a long way to help me and other coders use and support this library! 😃

**Comment by albbas** [comment]
Divvunspell is an integrated part of [giellakbd-android](https://github.com/divvun/giellakbd-android) and [giellakbd-ios](https://github.com/divvun/giellakbd-ios) and are built using [kdbgen](https://github.com/divvun/kbdgen). Information on how to use kdbgen is found here: https://divvun.github.io/kbdgen/ 

Hope this helps you on the way!

**Comment by snomos** [comment]
Also, both the README and LICENSE files have been added now.

**Comment by eddieantonio** [comment]
The updated README is awesome. Thanks, @snomos!
