### ISSUE TITLE
Differing behavior with different devices (crk)

### ISSUE THREAD

**Issue by aarppe** [divvun/divvunspell#33]
When I try to correct `nikiwapamaw` with divvunspell, I get as the first one the expected result of `nikîwâpamâw`, cf.

```
divvunspell suggest --archive tools/spellcheckers/crk.zhfst
Reading from stdin...
nikiwapamaw
Input: nikiwapamaw		[INCORRECT]
nikî-wâpamâw		30.360352
nikitâpamâw		36.151657
nikîmâpamâw		41.151657
naki-wâpamâw		42.151657
nika-wâpamâw		43.151657

```

This is also the behavior within LibreOffice, cf.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/15003407/172554109-0a2c0b83-f040-4740-81a1-773b0f6f643e.png">

However, when I try this with the mobile version of the speller, for whatever reason the second form (according to divvunspell) `nikitâpamâw` is suggested as the topmost correction, and `nikî-wâpamâw` is nowhere to be seen, cf.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/15003407/172555024-57348270-fbb9-4215-a8ce-031cb8126a6e.png">

**Comment by snomos** [comment]
This seems to be solved now, cf the following screen shot:

![IMG_BA7B755F9D38-1](https://user-images.githubusercontent.com/1255285/195165865-36342dfe-a631-40f9-8d3a-a32d40717498.jpeg)
