### ISSUE TITLE
Extra weight when initial letter is changed

### ISSUE THREAD

**Issue by snomos** [divvun/divvunspell#5]
One of the most glaring problems with our present spellers is that the suggestions get the same weight independently of where in the input string changes are made to produce the suggestions. This is contrary to what we know about the distribution of spelling errors, and cause a lot of noisy suggestions.

Errors are typically made in the middle of the words, not the beginning or end, so that the distribution of spelling errors' positions looks a lot like a gauss curve.

We are not able to build error models where the weights for one and the same edit changes depending on the position of the edit. A crude solution that would fix the most glaring errors would be a mechanically added weight to edits that are made to the first letter of the word. At best the initial letter weight would be configurable, for easy adjustments to the rest of the weighting scheme. The default could be `10`.

**Comment by bbqsrc** [comment]
Added in most recent commit.
