### ISSUE TITLE
Mixed-case strings accepted by hfst-ospell-office

### ISSUE THREAD

**Issue by snomos** [divvun/divvunspell#7]
The string _DavveVássján_ is accepted by the smj speller (attached, rename suffix to `zhfst`), although it should not. `hfst-ospell` does not accept it:

```
echo DavveVássján | hfst-ospell -S smj.zhfst | head -n 10
"DavveVássján" is NOT in the lexicon:
Corrections for "DavveVássján":
Davve-Vássján    27.590923 <== this is the intended correction
Davve-Vássjá    37.590923
...
```

I assume it is a bug in the case handling algorithm. For cases like these, the input string should be accepted IFF it is accepted exactly as given, or with the initial letter downcased, or all upper. Crucially, it should _not_ be accepted if it is _only_ accepted when all lowercased. In the example above, _DavveVássján_ is not an acceptable word, although _davvevássján_ is. But since neither _DavveVássján_ nor _davveVássján_ are accepted, the input string should be rejected, despite _davvevássján_ being accepted.

[smj.zip](https://github.com/hfst/hfst-ospell/files/3567106/smj.zip)

See also https://github.com/hfst/hfst-ospell/issues/46.

**Comment by bbqsrc** [comment]
```$ echo DavveVássján | hfst-ospell/bin/hfst-ospell -S ~/Downloads/smj.zhfst | head -n 10
"DavveVássján" is NOT in the lexicon:
Corrections for "DavveVássján":
avvevássján    34.590923
davvevássján    34.590923
navvevássján    35.590923
savvevássján    35.590923
Davve-Vássján    52.590923
Davve-Vássjás    62.590923
Davve-Vássjá    62.590923
Davve-Vássjáv    62.590923
```

```
Running `/Users/brendan/git/divvunspell/target/debug/divvunspell -z /Users/brendan/Downloads/smj.zhfst -sS 'DavveVássján'`
Input: DavveVássján             [INCORRECT]
avvevássján             34.590923
davvevássján            34.590923
navvevássján            35.590923
savvevássján            35.590923
Davve-Vássján           52.590923
Davve-Vássjá            62.590923
Davve-Vássjáj           62.590923
Davve-Vássjájn          62.590923
Davve-Vássjás           62.590923
Davve-Vássjáv           62.590923
```

Results are the same now. Closing :smile:
