### ISSUE TITLE
Suggestion differences between divvunspell and hfst-ospell(-office)

### ISSUE THREAD

**Issue by snomos** [divvun/divvunspell#9]
`divvunspell`:
```
AS:ain → AS:in

Result: Not in suggestions

Time: 36.038582 ms

Astan 53.04883
Asiin 55.3018
Askin 55.3018
Asodin 55.3018
Asolin 55.3018
Asošin 55.3018
Assin 55.3018
Astadin 55.3018
Astamin 55.3018
Asudin 55.3018
```

`hfst-ospell-office`:

```
AS:ain -> AS:in

Time: 1.018443 s

Result: 3

Ab:in
NS:in
AS:in
ASAin
Anjain
Annain
Antain
Anyain
Apain
Apiain
```

The correct suggestion in `hfst-ospell`has a weight of 72,916. The two top suggestions have the weight 70.301.

The most surprising thing is that the editing distance between the input `AS:ain` and the top `divvunspell` suggestion `Astan` is so big: `S-s, :->t, i->0` = 3. It should not be possible to generate most of the `divvunspell` suggestions, as we by default only allow two edit operations (specific string operations in the error model might override this default).

This is even more intriguing as the top `divvunspell` suggestion (`Astan`) *does not appear in the output of the error model*! Cf:

```
echo AS:ain | hfst-lookup -q errmodel.default.hfst
```

(It gives 553 732 suggestions, obviously most of them are garbage.)

Download the [se.zhfst](https://www.dropbox.com/s/a3nfohsnw5yhlsg/se.zhfst?dl=0) file for testing.

**Comment by snomos** [comment]
Another example along the same lines (`divvunspell` first):

```
AUF´era → AUF:ára

Result: Not in suggestions

Time: 59.488496 ms

Ampera 55.3018
Busera 55.3018
Sumera 55.3018
Uføra 55.3018
Ankera 78.609375
Aalera 80.3018
Aasera 80.3018
Adgera 80.3018
Adlera 80.3018
Agdera 80.3018
```

`hfst-ospell-office`:

```
AUF´era → AUF:ára

Result: Not in suggestions

Time: 0.504368 s

AU-lera
AUF-lera
AUF-ura
AUF-ára
AU-Gera
AUF-Vera
AU-Bera
AU-Nera
AUF-Tera
AUF-Sera
```

Again, all suggestions by `divvunspell` seem to have an editing distance of 3.

**Comment by snomos** [comment]
Consider the following `divvunspell` output:

```
Afrihkas → Afrihkás

Result: Top suggestion

Time: 33.923317 ms

Afrihkás 44.38672
Antihkas 55.3018
Arnihkas 55.3018
Fabrihkas 55.3018
Fráhkas 55.3018
Lyrihkas 55.3018
Paprihkas 55.3018
Trihkas 55.3018
```

The interesting suggestion here is the fourth one: `Fabrihkas`. It has an editing distance of 3 if one considers `A` and `a` different symbols, but an editing distance of 2 if they are treated as the same symbol (the same is true also for `Paprihkas`). Could that be the case, that there is some case folding going on, causing confusion for the error model?

**Comment by snomos** [comment]
Another case:

```
Ahkkanasjohkii → Áhkkanasjohkii

Result: Suggestion 2

Time: 62.369366 ms

Ráhkkanasjohkii 53.3018
Áhkkanasjohkii 60.3018
Faskkanasjohkii 67.3018
Rokkanasjohkii 67.3018
Šikkanasjohkii 67.3018
Ahkefanasjohkii 79.3018
Ahkevanasjohkii 79.3018
Ahkečanasjohkii 79.3018
Cahkkananjohkii 79.3018
```

`hfst-ospell-office`:

```
Ahkkanasjohkii → Áhkkanasjohkii

Result: Suggestion 1

Time: 0.299952 s

Áhkkanasjohkii
Rokkanasjohkii
Šikkanasjohkii
Ráhkkanasjohkii
Áhkkanas-johkii
Akkanas-johkii
Faskkanasjohkii
Ahkečanasjohkii
Cahkkananjohkii
Ahkefanasjohkii
```

Now compare this with `hfst-ospell` (CLI), which also gives weight info:

```
$ echo Ahkkanasjohkii | hfst-ospell -S tools/spellcheckers/fstbased/desktop/hfst/se.zhfst | head -n 12
"Ahkkanasjohkii" is NOT in the lexicon:
Corrections for "Ahkkanasjohkii":
Áhkkanasjohkii    60.301800
rokkanasjohkii    67.301804
šikkanasjohkii    67.301804
ráhkkanasjohkii    67.301804
Áhkkanas-johkii    10132.301758
Akkanas-johkii    10132.301758
```

The target correction has the same weight in both, but the # 1 in `divvunspell` has a substantially lower weight, while the same suggestion (with lower-case r because `hfst-ospell` does not do case handling) has a **higher** weight.

**Comment by snomos** [comment]
One more diff. `divvunspell`:

```
Alaraudajoki → Alaraudanjoki

Result: Top suggestion

Time: 109.126947 ms

Alaraudanjoki 59.301758
```

`hfst-ospell`:

```
$ echo 'Alaraudajoki' | hfst-ospell -S tools/spellcheckers/fstbased/desktop/hfst/se.zhfst | head -n 10
"Alaraudajoki" is NOT in the lexicon:
Corrections for "Alaraudajoki":
Alaraudanjoki    59.301758
Alaraudanjokin    80.301804
Alaraudanjokis    80.301804
Alaraudanjokii    80.301804
Alaraudanjoki-    20132.302734
```

Although `divvunspell` is better in the sense that it only suggests the intended correction, it is still strange that none of the other suggestions in `hfst-ospell` are present also in `divvunpell` — only the last one has a weight above the default kill limit (`10 000`).

**Comment by bbqsrc** [comment]
> Although `divvunspell` is better in the sense that it only suggests the intended correction, it is still strange that none of the other suggestions in `hfst-ospell` are present also in `divvunpell` — only the last one has a weight above the default kill limit (`10 000`).

If `Alaraudanjoki    59.301758` is found first, then the new weight limit is `59.301758` and anything higher than that will not be added to the list.

**Comment by snomos** [comment]
> > Although `divvunspell` is better in the sense that it only suggests the intended correction, it is still strange that none of the other suggestions in `hfst-ospell` are present also in `divvunpell` — only the last one has a weight above the default kill limit (`10 000`).
> 
> If `Alaraudanjoki 59.301758` is found first, then the new weight limit is `59.301758` and anything higher than that will not be added to the list.

But how do you know that `Alaraudanjoki 59.301758` is the correct suggestion? There is no context knowledge.

**Comment by bbqsrc** [comment]
These issues should now all be resolved.
